### PR TITLE
Fixed a bug in HandleNick and another in HandleKick.

### PR DESCRIPTION
**Pull request by khawajaumarfarooq**
Also added the NuGet package source to the repository.

### CODE REVIEW

**Comment by fahadash** [comment]
The change history looks unreadable. But the only things changed were the following

HandleKick was using case sensitive comparison to check whether or not it is "me" who got kicked and was failing because of how the cases are preserved at some servers. So this PR changes that to Case-Ignore comparison

Other bug that was fixed was a real big one. That bug was with HandleNick() which was not updating the internal object models when a user changes his nick. The consequence of that bug? When a user gets kicked AFTER the fact that he has changed his nick and object models that hold his nick weren't updated are still reflecting the old nick are not found in the Collections, and HandleKick() crashes with a KeyNotFoundException. Also, HandleKick was using case-sensitive comparison to check if it is "me" who got nick changed, this PR changed it to case-ignore.

**Comment by SirCmpwn** [comment]
The nuget package is unofficial. Please remove it.

**Comment by fahadash** [comment]
Its not official. He put it up there to make the build process easy and add a single source for the releases. If you want to maintain the Nuget package yourself, then it would make sense for him to remove. Since you did not have one in there, someone had to do it.

**Comment by SirCmpwn** [comment]
I do not want to maintain a nuget package upstream. Please remove it.

**Comment by fahadash** [comment]
Why do you not want to do it? And why is there an "I" ? Aren't we going to value the opinions of all the contributors as opposed to one person telling everybody what to do?

**Comment by khawajaumarfarooq** [comment]
Fair enough, SirCmpwn. I can understand your view. It isn't a file that you should have to deal with. I shall remove it and resend another pull-request. Apologies for any inconvenience.

**Comment by SirCmpwn** [comment]
>Why do you not want to do it? And why is there an "I" ? Aren't we going to value the opinions of all the contributors as opposed to one person telling everybody what to do?

I am under no obligation to maintain this project in any specific way. If you want a nuget package, you're welcome to publish one yourself and shoulder the burden of maintaining it. Don't presume to tell me that I need to do that for you.

**Comment by fahadash** [comment]
@SirCmpwn Please disregard that. I thought you were trying to prevent Chatsharp from being Nuget.org by anyone. My bad.

**Pull request closed without merging**
