### PR TITLE
Add support for IRCv3 message tags

### PR DESCRIPTION
**Pull request by RockyTV**
As defined in IRCv3, using the following spec as reference: http://ircv3.net/specs/core/message-tags-3.2.html

### CODE REVIEW

**Comment by SirCmpwn** [comment]
>Server MUST NOT add a tag to messages, if client didn’t request the capability which enables the tag using CAP REQ.

**Comment by RockyTV** [comment]
A few lines below:
> Client and server MAY parse the tags even without any capabilities enabled. They SHOULD ignore tags of capabilities which are not enabled.

**Comment by SirCmpwn** [comment]
Still, send the req or complaint servers won't send them to us anyway.

**Comment by SirCmpwn** [comment]
We need a caps subsystem to do this sort of stuff.

**Comment by RockyTV** [comment]
Yes, the lib has to send a `CAP LS` when connecting to the server to get the list of capabilities. Will work on it.

**Comment by RockyTV** [comment]
Capability subsystem implemented in #79. Need to get this one merged to fully support the `server-time` capability.

**Pull request merged**
