### PR TITLE
Add a variable to stop ChatSharp from writing stuff to console

### PR DESCRIPTION
**Pull request by RockyTV**
Perhaps should I remove it from the constructor and make it a get;set; bool?

### CODE REVIEW

**Comment by SirCmpwn** [comment]
These are leftover debug messages that should just be removed entirely.

**Comment by RockyTV** [comment]
Why not this, then, if they are debug messages?
```csharp
#if DEBUG
                Console.WriteLine("TCP transmission complete");
            #endif
```

**Comment by SirCmpwn** [comment]
No, they just need to be removed.

**Comment by RockyTV** [comment]
Should this `Console.WriteLine("Sending queued messages (currently writing: {0})", IsWriting);` be removed too?

**Comment by SirCmpwn** [comment]
Yes.

**Comment by RockyTV** [comment]
Updated my commit.

**Comment by SirCmpwn** [comment]
Thanks!

**Pull request merged**
